### ISSUE TITLE
Ability to emit multiple parse errors for a single token

### ISSUE THREAD

**Issue by squeek502** [watzon/zhtml#3]
In looking at what it would take to fix some of the html5lib tests, I noticed that in certain situations multiple errors can sometimes be expected when emitting a single token. For example:

```
<p></p attr/>
```

According to the [spec in 12.2.5 Tokenization](https://html.spec.whatwg.org/multipage/parsing.html#tokenization):

> When an end tag token is emitted with attributes, that is an end-tag-with-attributes parse error.

> When an end tag token is emitted with its self-closing flag set, that is an end-tag-with-trailing-solidus parse error.

This means that when emitting an EndTag where both of those are true, `nextToken` should error once with `EndTagWithAttributes` and then again with `EndTagWithTrailingSolidus`, but zhtml doesn't currently make this possible as far as I can tell, so it seems like some type of error queue will end up being necessary (i.e. in nextToken, if there is an error in the queue, then just pop it off and return it immediately).

(side note: html5lib-tests doesn't have this specific test where both errors are emitted for the same end tag, but I believe this is the behavior the spec expects)

**Comment by watzon** [comment]
Damn I was hoping to avoid that, but oh well. If it can't be helped it can't be helped.
